name: Print hello world
on: 
  push:
jobs:
  print:
    runs-on: macOS-latest
    defaults:
        run: 
        working-directory: backend
    steps:
      - name: I dependancy
        run: npm ci
      - name: I run the tests
        run: npm test

